### ISSUE TITLE
How to uninstall\disable wallpaper?

### ISSUE THREAD

**Issue by cosmmmic** [kush-agra/Dynamic_Walls-app#1]
Just wondering how to delete this. Thanks

**Comment by kush-agra** [comment]
Deleting the app normally would technically disable it too but a better way would be to go to the terminal and type 'launchctl unload -w ~/Library/LaunchAgents/Dynamic_walls.Scheduler.plist`

if you use a third party uninstalling app on your mac that should take care of it automatically too
