### ISSUE TITLE
Wallpaper only updates if desktop is visible

### ISSUE THREAD

**Issue by GoldenChaos** [kush-agra/Dynamic_Walls-app#2]
If I have apps open in fullscreen, the wallpaper won't update unless I switch back to a desktop. With multiple monitors, this means that wallpapers can be out of sync.

**Comment by kush-agra** [comment]
Did you try it with multiple monitors? I haven't tested it on multiple monitors, and yes that is a limitation It also doesn't work with spaces, haven't found a proper way to do that,but they should get in sync very soon again

**Comment by GoldenChaos** [comment]
Yes, I have a MBP connected to an LG UltraFine and the two monitors' wallpapers regularly fall out of sync because I use spaces.

**Comment by kush-agra** [comment]
Yea and there is no good way to fix that :( I had listed that as a limitation already, newly built spaces should have the proper wallpaper but old spaces can sometimes have old wallpapers :/
