### ISSUE TITLE
Default dynamic macOS wallpaper timings and wallpapers f***ed.

### ISSUE THREAD

**Issue by alxdxx** [kush-agra/Dynamic_Walls-app#3]
Somehow it got messed up and when dynamic wallpaper selected as normally it shows only a static pre-sunset mojave background (in white & dark theme).

- Uninstalled as you mention.

- How to fix that (recover original as expected function of dynamic wallpaper)

**Comment by alxdxx** [comment]
also updating from beta 2 to beta 3 and revised beta 3 (2 days ago - latest update) did not fix the issue. it must be dynamic_walls and something past the scheduler?? (everything has been deleted but why is the dynamic wallpaper timings broken and image is static? why is the dynamic wallpaper static ????? Please help ....!!!!

**Comment by alxdxx** [comment]
i am sorry. maybe the beta is now broken from Apple and its not your fault?? Somehow this .heic fixes it. 

https://mega.nz/#!fUB1CQLa!UA9v4etwoZRdPz4C8IhcMBatyDeoIgJRKs4UUNOMluw

**Comment by kush-agra** [comment]
My primary and only mac is not on the beta anymore I can't test it :/

**Comment by marcsphd** [comment]
Are you referring about Mojave Beta? The dynamic paper only works fully (with day and night times) when you DO NOT select night mode. If you do so, the dynamic wallpaper changes only throughout night times. It seems that it is not a bug, it is a feature!
