### ISSUE TITLE
Can't Get To Dark Mode

### ISSUE THREAD

**Issue by ACRONN** [kush-agra/Dynamic_Walls-app#5]
Hi,

The actual app in processing the pictures and applying them is amazing but I realised that it switched my dark mode back to light mode. I checked my general section to see what was applied and it said I was using dark mode but I wasn't at all. Even going back to light mode and back to dark mode would just activate dark for a bit then auto switch to light again. The only way I found to fix this was to uninstall the app.

Hopefully this issue I'm having will get fixed maybe in a future update or otherwise

**Comment by kush-agra** [comment]
Just say no to use dynamic theme after choosing the images folder, the dynamic theme sets the theme to light/dark based on the time
