### ISSUE TITLE
The App won't  work

### ISSUE THREAD

**Issue by AlexyFoxy** [kush-agra/Dynamic_Walls-app#7]
The app won't work(this is the first time I try it).

I opened the app and it asked for the wallpaper folder (choose the folder of the fixed.png), then asked for the dark theme then(I choose No and tried Yes), then the terminal opened and they (app and terminal) quits and nothing happen.

I noticed that Dynamic_Walls.Scheduler.plist doesn't being written to lunch agent folder(it is not there at: ~/Library/LaunchAgents/Dynamic_walls.Scheduler.plist)

**Comment by kush-agra** [comment]
Hey, thanks for letting me know,  i've got no idea as of now, I have exams and shall be busy with those for a month, seems like something the newest update of mojave did 😫, i'll look into it when i get time, thanks :3

**Comment by AlexyFoxy** [comment]
Thanks for your concern I appreciate it, best wishes for your exams.

I tried it on both high Sierra and Mojave with no use (The folder of launchAgents doesn't exist on Mojave nor the plist file, and for High Sierra the plist file doesn't been written)
PS: I am on Build 18A391 for Mojave(On unsupported device using patching tool) and on Build 17G3025 for High Sierra.
I wonder if you can tweak it to work on High Sierra OS? (That's will be convenient and appreciated)

Again, I appreciate your concern and all the best for exams.

**Comment by kush-agra** [comment]
Thank you so much for the best wishes :') math scares me haha 

can you try running 

`( /usr/bin/sudo launchctl list ; launchctl list ) |
grep -v 'com.apple.'`

see if it lists the plist, it's weird because it should be working on high sierra, it did last I checked, but sorry again I'll only be able to look into it after the 28'th of this month

**Comment by AlexyFoxy** [comment]
I checked and it did not return its name, just other plists for programs I use.
Also upon its installation it did not ask me for permissions(where you find it in Privacy tab in System Preferences) as it did on Mojave.

Wish you all the best in your math test, sorry to trouble you with such things as you are busy, and thanks for your fast response much appreciated.

**Comment by kush-agra** [comment]
Soo..I spent the past 2 days trying to see what could be causing it, uninstalled-reinstalled a few times and saw a few tiny problems but nothing major to prevent it from working, it's working for me :/ 

Can you try setting up the [script manually maybe](https://github.com/kush-agra/Dynamic_Walls)

also as you said it didn't ask for permission ensure the app has permission for accessing location services, and the app is in the applications folder, right? although it shouldn't matter one bit but also try running it from the applications folder to be sure

**Comment by Alonizi** [comment]
> Soo..I spent the past 2 days trying to see what could be causing it, uninstalled-reinstalled a few times and saw a few tiny problems but nothing major to prevent it from working, it's working for me :/
> 
> Can you try setting up the [script manually maybe](https://github.com/kush-agra/Dynamic_Walls)
> 
> also as you said it didn't ask for permission ensure the app has permission for accessing location services, and the app is in the applications folder, right? although it shouldn't matter one bit but also try running it from the applications folder to be sure

the app was also not working for me , i tried it manually and it worked !
