### ISSUE TITLE
Can't switch back to static wallpapers

### ISSUE THREAD

**Issue by jjgleim** [kush-agra/Dynamic_Walls-app#8]
When this app is installed, my wallpapers were stuck on only using the default system Mojave dynamic wallpaper.  I couldn't switch back to normal static wallpaper.  Had to uninstall and delete the app to get my wallpaper working again.  Why does this app try to always set the wallpaper to be dynamic?  Just concentrate on helping folks create the dynamic wallpapers and let users worry about selecting which wallpaper they want to use.

Thanks!

**Comment by kush-agra** [comment]
One currently needs to disable the launch agent to stop the script from working as it says in the uninstallation section

I'll add an easier way to disable it, thank you :)
